name: Run Auto Generate API Docs
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Run Code Tests]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm

      - name: Clean install dependencies
        run: npm ci

      - name: Start server
        env:
          APP_ENV: development
          APP_PORT: 3000
          SPOTIFY_COOKIE: loremipsumdolor # Random value to bypass env validation
        run: npm run start &

      - name: Build API documentations
        run: |
          npx wait-on tcp:3000
          npm run build:docs

      - name: Commit changed docs to remote branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: docs/*
          commit_message: 'docs(api): add auto generated api docs [skip ci]'
