name: Run Code Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Clean install dependencies
        run: npm ci

      - name: Run tests and collect coverage
        run: npm run test:ci

      - name: Publish test report
        uses: mikepenz/action-junit-report@v3
        if: ${{ github.event_name == 'pull_request' && always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: junit.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
